### ISSUE TITLE
Overriding styles

### ISSUE THREAD

**Issue by foobar8675** [dharness/react-chat-window#27]
Is there a way to override the styles? If not, would you be open to taking a PR?

**Comment by dharness** [comment]
The best way to override the styles currently would be to use a wrapper div and select the elements directly inside of it:
``` html
<div clasName="chat-wrapper">
    <Launcher />
</div>
```

``` css
.chat-wrapper .sc-launcher {
    background: plum;
}
```

That said, I'm open to alternatives and would totally accept a PR if we can agree on something. What would you like that to look like?
